import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mathSidebar: [{type: 'autogenerated', dirName: 'math'}],
  csSidebar: [{type: 'autogenerated', dirName: 'cs'}],
  physicsSidebar: [{type: 'autogenerated', dirName: 'physics'}],
  chemSidebar: [{type: 'autogenerated', dirName: 'chemistry'}],
  qisSidebar: [{type: 'autogenerated', dirName: 'quantum-information-science'}],
};

export default sidebars;
